### PR TITLE
adding Icelandic and translation files updates

### PR DESCRIPTION
**Pull request by mtrz**
- adding new Icelandic language: is-IS
(according to: [UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages) it should be supported in the app)
- xlf and resw translation files updates

### CODE REVIEW

**Comment by mfkl** [comment]
Hi Michi,

Thank you for the PR! A few remarks:

- I think you forgot to add the `IcelandicLanguage` to the English resw file. 
- You (or your tool) added a lot comments in the beginning of some resw files along with the XSD schemas. I don't think we need those.
- Switching to some languages do not seem to work anymore when I gave it a try with your changes. I assume you have not tested this with a local build (as it's not really straightforward to get it started). That's OK, I'll figure it out and let you know.

**Comment by mtrz** [comment]
Thanks Martin, I have made some corrections to the files:
- the English resw file has `IcelandicLanguage`
- all other resw files are without the XSD schemas
- removed newline at end of all resw files as the previous files didn't have it
- changes the string order a little bit in both files to be more meaningful for the translators

If you can point out the broken langs I will check these. In some cases Transifex comment out some special characters differently than that was before or one of the translator adds extra new lines breaks, but I think it can be solved.

**Comment by mfkl** [comment]
Hi @mtrz,

Thanks for your edits. 

When building the code with your PR, the multilingual app toolkit basically leaves all the resw files empty, which is why switching languages does not work anymore.

I suspect you changed some needed XML attributes or properties that affect the resw file generation, could not find which. Disabling the MAT makes this behavior go away, but the Icelandic language does not work. All others fine.

**Comment by mfkl** [comment]
Merged, thank you!

**Pull request closed without merging**
