### PR TITLE
Fixed possibility to go beyond the border values in video settings.

### PR DESCRIPTION
**Pull request by 23rd**
This PR fixes a couple bugs in playback settings window.

If user sets a value of the audio delay (or the subtitle delay) on a slider (for example 15) and after this increases the value by `+` button, in the end he will get 3015 ms instead of 3000.
Visual gif is below.

And the second bug is related to the subtitle delay. It's completely broken, the value must not be multiplied by 1000.
Even though this issue is fixed by single line, I split the PR into two commits because I think it's another bug not related to the previous one.   

Both issues are reproduced in Xbox.

By the way, I replaced the repeated numbers with int variables. This will make it easier to change steps and limits in the future.

heh3

### CODE REVIEW

**Comment by mfkl** [comment]
Thanks for your PR!

I merged your first patch https://github.com/videolan/vlc-winrt/pull/10/commits/ee4249899ae11ce60c4c58555d1fa774b44184ce

For this one https://github.com/videolan/vlc-winrt/pull/10/commits/1e5caad3b2404a69be64a469d7490469c354b9cb, there is indeed a UI issue but your fix kinda disable the feature as the value given to the mediaplayer is too low to make a real difference in the perceived delay. 

Perhaps a good idea would be to keep the `* 1000` and to add a `/ 1000` in the getter. What do you think?

**Comment by 23rd** [comment]
Thanks for merging of the first commit.

>Perhaps a good idea would be to keep the `* 1000` and to add a `/ 1000` in the getter. What do you think?

Does that make sense? Both last sliders are the same, then why do we need to make such a difference in the values?
If you want `a real difference` then the limits should also be increased to `30 seconds` and `-30 seconds`, but I think this is huge delay.

**Comment by mfkl** [comment]
The docs says we are talking about **micro**seconds, not **milli**seconds. So the `1000` operation looks justified to get the 3s delay range. https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#ga98a515c9a91f3ac322fc720ac301f985
https://en.wikipedia.org/wiki/Microsecond

Looking at this old commit https://github.com/videolan/vlc-winrt/commit/4f0359ef, it seems the audio delay should get the same treatment as it used to have.

**Comment by 23rd** [comment]
Okay, now I got it completely.
All this time I thought the library worked with milliseconds, sorry.
Now the delays work correctly.

**Comment by mfkl** [comment]
Merged, thanks! https://github.com/videolan/vlc-winrt/commit/a67dd7dedfd9976e1628adc5384df0778634a560

**Comment by 23rd** [comment]
@mfkl Just wondering when to expect an updated version? :)

**Comment by mfkl** [comment]
I'm gonna focus on that now. However it's tricky as we have some issues on winrt with several of our numerous dependencies.

**Comment by 23rd** [comment]
@mfkl Any news? Seems like Xbox One still has no updates for VLC. =(

**Comment by mfkl** [comment]
Blocked by a chromecast issue on mobile. Might make a release without that fix tho.

**Pull request closed without merging**
