### PR TITLE
syncing xls files to the same format 

### PR DESCRIPTION
**Pull request by mtrz**
- all xlf files have the same spacing format now
- reverted the html character conversion from Tx. MS don't use is either, like here:
https://github.com/Microsoft/vs-mef/tree/master/src/Microsoft.VisualStudio.Composition.LocalizationShell/MultilingualResources

### CODE REVIEW

**Comment by mfkl** [comment]
Is this ready to be merged?

**Comment by mtrz** [comment]
Yes it can be merged, now all files are in the same format and will have it in the future.
It's the same structure that also MS uses in his xlf files, so this could be solved if we don't have any further problems in the app.

**Comment by mfkl** [comment]
I only cherry pick your last 3 commits right? The rest has already been pushed with https://github.com/videolan/vlc-winrt/commit/5aedecc4000443f0abc5e2521b46f3dac7c81033.

**Comment by mtrz** [comment]
That's right, all other changes were already committed. If this won't affect the resw file generating and don't produce new problems, we will use this format.

**Comment by mfkl** [comment]
Cherry picked with 
https://github.com/videolan/vlc-winrt/commit/d47dfa0183d34d786bd5a6f1cd376115152d309c
https://github.com/videolan/vlc-winrt/commit/2bc3f8f562bddcb729f7e734fdfbd95b29d33910
https://github.com/videolan/vlc-winrt/commit/bd5cf06c6682d68795b2a212a626e15329694c63

MLAT automatic generation update https://github.com/videolan/vlc-winrt/commit/6702bb08c67bb5067eb1a924768db153eb1269d2

**Pull request closed without merging**
